### ISSUE TITLE
Folder create with name starting from small letter FAILS

### ISSUE THREAD

**Issue by sujit1779** [justmarks/SmugMug.NET.v2#2]
Hi,

When trying to create a Folder using SmugMug.NET.V2 and if folder name starts with small letter, it fails. But when it starts with a capital letter, it succeeds. Is this the issue with Smugmug guys or with this wrapper?
Thanks.

**Comment by justmarks** [comment]
Resolved with 85e0bf13769ffa271132c07242607e060372d0ea
